name: Deploy Model to Azure ML

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Register Azure ML Resource Provider
        run: az provider register --namespace Microsoft.MachineLearningServices

      - name: Set Azure Subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Verify Subscription
        run: az account show

      - name: Install Azure ML CLI
        run: az extension add --name ml

      - name: Deploy Model as Web Service
        run: |
          az ml online-endpoint create --name heart-disease-endpoint \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --workspace-name ${{ secrets.AZURE_ML_WORKSPACE }}
