name: Deploy Model to Azure ML

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check if Endpoint Exists
        id: check_endpoint
        run: |
          if az ml online-endpoint show --name heart-disease-endpoint \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --workspace-name ${{ secrets.AZURE_ML_WORKSPACE }}; then
            echo "ENDPOINT_EXISTS=true" >> $GITHUB_ENV
          else
            echo "ENDPOINT_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Create Endpoint (If Not Exists)
        if: env.ENDPOINT_EXISTS == 'false'
        run: |
          az ml online-endpoint create --name heart-disease-endpoint \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --workspace-name ${{ secrets.AZURE_ML_WORKSPACE }}

      - name: Update Existing Endpoint (If Exists)
        if: env.ENDPOINT_EXISTS == 'true'
        run: |
          az ml online-endpoint update --name heart-disease-endpoint \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --workspace-name ${{ secrets.AZURE_ML_WORKSPACE }}
